app:
  secret: |
    https://www.ibm.com/docs/en/sdk-java-technology/8?topic=processes-secret-key-cryptography
    With secret-key cryptography, both communicating parties, Alice and Bob, use the same key to encrypt and decrypt the messages. Before any encrypted data can be sent over the network, both Alice and Bob must have the key and must agree on the cryptographic algorithm that they will use for encryption and decryption
    One of the major problems with secret-key cryptography is the logistical issue of how to get the key from one party to the other without allowing access to an attacker. If Alice and Bob are securing their data with secret-key cryptography, and if Charlie gains access to their key, then Charlie can understand any secret messages he intercepts between Alice and Bob. Not only can Charlie decrypt Alice's and Bob's messages, but he can also pretend that he is Alice and send encrypted data to Bob. Bob won’t know that the message came from Charlie, not Alice.
    After the problem of secret key distribution is solved, secret-key cryptography can be a valuable tool. The algorithms provide excellent security and encrypt data relatively quickly. The majority of the sensitive data sent in an TLS session is sent using secret-key cryptography.
    Secret-key cryptography is also called symmetric cryptography because the same key is used to both encrypt and decrypt the data. Well-known secret-key cryptographic algorithms include Advanced Encryption Standard (AES), Triple Data Encryption Standard (3DES), and Rivest Cipher 4 (RC4).
server:
  port: 50051
postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: password
  dbname: postgres
  sslmode: disable
jwt:
  issuer: "localhost"
  secret_key: |
    -----BEGIN EC PRIVATE KEY-----
    MIGkAgEBBDAdJDHValeWcWFcTNuoHkQw7pwqB9bs7DQyZOnZsl6OlVt4bAhTUH5H
    wjOh+RAyQKegBwYFK4EEACKhZANiAAR7h/3UNZ37q6+N/V6LZDvfCwKuAEfyAVU2
    v7yGikguwjZQfzZ6cqypY2M+Mhy/fIpFEP9dkL4SKkA3aBzIMAmwNkT9GpieSsk9
    FQZ1imor3O39JIe011bfq2lnwJRn7+4=
    -----END EC PRIVATE KEY-----

